//! `mati review` — interactive queue for confirmed=false gotcha candidates.
//!
//! Drains the backlog of Layer 0 stubs that need developer confirmation
//! before they can be injected by the pre-read hook.
//!
//! Candidates: `gotcha:*` records with `GotchaRecord.confirmed == false` and
//! `lifecycle == Active`. Includes Layer 0 stubs (Suppressed quality) so
//! developers can review and improve them before the injection gate. Sorted by
//! `access_count DESC` so the most-accessed files surface first.
//!
//! Actions per candidate:
//! - **Confirm** — sets `confirmed=true`, promotes source to `DeveloperManual`,
//!   sets confidence to 0.80, adds `HasGotcha` edges. Record is now injectable.
//! - **Edit** — inline rule/reason edit, then offers to confirm immediately.
//!   For severity/files/URL changes use `mati gotcha edit <key>` directly.
//! - **Skip** — leaves as candidate, will reappear on next `mati review`.
//! - **Delete** — tombstones the record and removes graph edges.
//! - **Quit** — stop the session; unreviewed candidates remain for next time.

use std::io::{self, BufRead, IsTerminal, Write as _};
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::Result;
use clap::Args;

use mati_core::graph::{EdgeKind, Graph};
use mati_core::health::quality;
use mati_core::store::{
    ConfidenceScore, GotchaRecord, Record, RecordLifecycle, RecordSource, TombstoneReason,
};

use super::colors;
use super::proxy::StoreProxy;

// ── Args ─────────────────────────────────────────────────────────────────────

#[derive(Args)]
pub struct ReviewArgs {}

// ── Entry point ───────────────────────────────────────────────────────────────

pub async fn run(_args: ReviewArgs) -> Result<()> {
    let use_color = io::stderr().is_terminal();
    let cwd = std::env::current_dir()?;

    let candidates = {
        let proxy = StoreProxy::open(&cwd).await?;
        let result = collect_candidates(&proxy).await?;
        proxy.close().await?;
        result
    };

    if candidates.is_empty() {
        println!("No candidates pending review.");
        println!("Candidates are generated by `mati init` (co-change pairs, revert rate, etc.).");
        println!("Check `mati gaps` to see what else needs attention.");
        return Ok(());
    }

    let total = candidates.len();

    let (cyan, green, yellow, gray, bold, reset) = if use_color {
        (
            colors::CYAN,
            colors::GREEN,
            colors::YELLOW,
            colors::GRAY,
            colors::BOLD,
            colors::RESET,
        )
    } else {
        ("", "", "", "", "", "")
    };

    eprintln!("\n{bold}{total} candidate{}{reset} pending review", if total == 1 { "" } else { "s" });
    eprintln!("{gray}[c]onfirm · [e]dit · [s]kip · [d]elete · [q]uit{reset}\n");

    let stdin = io::stdin();
    let mut lines = stdin.lock().lines();

    let mut n_confirmed = 0usize;
    let mut n_deleted = 0usize;
    let mut n_skipped = 0usize;

    for (i, record) in candidates.into_iter().enumerate() {
        let key = record.key.clone();

        // ── Display candidate ─────────────────────────────────────────────

        eprint!("{gray}[{}/{}]{reset}  {cyan}{key}{reset}", i + 1, total);

        // Show tag hint (e.g. co-change, auto-generated)
        let tags: Vec<&str> = record.tags.iter().map(|s| s.as_str()).collect();
        if !tags.is_empty() {
            eprintln!("  {gray}{}{reset}", tags.join(", "));
        } else {
            eprintln!();
        }

        if let Some(g) = record.payload_as::<GotchaRecord>() {
            eprintln!("  {bold}Rule:{reset}   {}", g.rule);
            if !g.reason.is_empty() {
                eprintln!("  {bold}Reason:{reset} {}", g.reason);
            }
            eprintln!("  {bold}Files:{reset}  {}", g.affected_files.join(", "));
        } else {
            eprintln!("  {}", record.value);
        }

        let q_color = if record.quality.value >= 0.6 {
            green
        } else if record.quality.value >= 0.4 {
            yellow
        } else {
            colors::RED
        };
        eprintln!(
            "  {gray}quality {q_color}{:.2}{reset}  {gray}confidence {}{:.2}{reset}",
            record.quality.value, gray, record.confidence.value
        );
        eprintln!();

        // ── Prompt loop ───────────────────────────────────────────────────

        loop {
            eprint_prompt("[c/e/s/d/q]: ", use_color);
            let input = read_line(&mut lines)?;

            match input.to_lowercase().trim() {
                "c" | "confirm" => {
                    confirm_candidate(&cwd, &key).await?;
                    eprintln!("{green}✓{reset} Confirmed. Ready for injection.");
                    n_confirmed += 1;
                    break;
                }
                "e" | "edit" => {
                    if let Some(g) = record.payload_as::<GotchaRecord>() {
                        let did_confirm =
                            edit_inline(&cwd, &key, &g, &mut lines, use_color).await?;
                        if did_confirm {
                            n_confirmed += 1;
                        } else {
                            n_skipped += 1;
                        }
                    } else {
                        eprintln!("  {yellow}Cannot edit: not a GotchaRecord payload.{reset}");
                        eprintln!("  Use `mati gotcha edit {key}` instead.");
                        n_skipped += 1;
                    }
                    break;
                }
                "s" | "skip" | "" => {
                    eprintln!("{gray}Skipped.{reset}");
                    n_skipped += 1;
                    break;
                }
                "d" | "delete" => {
                    delete_candidate(&cwd, &key).await?;
                    eprintln!("{yellow}Deleted.{reset}");
                    n_deleted += 1;
                    break;
                }
                "q" | "quit" => {
                    let remaining = total.saturating_sub(i);
                    println!(
                        "\nStopped. {n_confirmed} confirmed, {n_deleted} deleted, \
                         {n_skipped} skipped, {remaining} remaining."
                    );
                    return Ok(());
                }
                _ => {
                    eprintln!("  {yellow}?{reset} Enter c / e / s / d / q");
                }
            }
        }

        eprintln!();
    }

    println!(
        "Review complete: {n_confirmed} confirmed, {n_deleted} deleted, {n_skipped} skipped."
    );
    Ok(())
}

// ── Candidate collection ──────────────────────────────────────────────────────

/// Scan `gotcha:*` for Active records with `confirmed=false`.
/// Includes Layer 0 stubs (quality < 0.4, Suppressed tier) so developers can
/// review and promote auto-generated candidates via `mati improve` before
/// confirming. The injection quality gate (>= 0.4) is enforced separately.
/// Sorted by `access_count DESC` — most-accessed candidates first.
async fn collect_candidates(store: &StoreProxy) -> Result<Vec<Record>> {
    let all = store.scan_prefix("gotcha:").await?;
    let mut candidates: Vec<Record> = all
        .into_iter()
        .filter(|r| {
            if !matches!(r.lifecycle, RecordLifecycle::Active) {
                return false;
            }
            match r.payload_as::<GotchaRecord>() {
                Some(g) => !g.confirmed,
                None => false,
            }
        })
        .collect();

    // Most-accessed first — these are the ones Claude is already asking about.
    candidates.sort_by(|a, b| b.access_count.cmp(&a.access_count));
    Ok(candidates)
}

// ── Actions ───────────────────────────────────────────────────────────────────

/// Promote a candidate to confirmed:
/// - `GotchaRecord.confirmed = true`
/// - source → `DeveloperManual`, confidence.value → 0.80
/// - `HasGotcha` graph edges added for all affected files
async fn confirm_candidate(cwd: &Path, key: &str) -> Result<()> {
    let proxy = StoreProxy::open(cwd).await?;

    let mut record = proxy
        .get(key)
        .await?
        .ok_or_else(|| anyhow::anyhow!("record not found: {key}"))?;

    let mut gotcha: GotchaRecord = record
        .payload_as()
        .ok_or_else(|| anyhow::anyhow!("{key} is not a gotcha record"))?;

    let now = now_secs();
    gotcha.confirmed = true;
    record.payload = serde_json::to_value(&gotcha).ok();
    record.source = RecordSource::DeveloperManual;
    record.confidence.value =
        ConfidenceScore::base_for_source(&RecordSource::DeveloperManual);
    record.confidence.confirmation_count =
        record.confidence.confirmation_count.saturating_add(1);
    record.updated_at = now;
    record.version.logical_clock += 1;
    record.version.wall_clock = now;

    proxy.put(key, &record).await?;

    // Add HasGotcha edges so mem_bootstrap can find this gotcha via graph traversal.
    if proxy.is_direct() {
        let store = proxy.into_store();
        let mut graph = Graph::load(store).await?;
        for af in &gotcha.affected_files {
            let file_key = format!("file:{af}");
            graph.add_edge(&file_key, EdgeKind::HasGotcha, key).await?;
        }
        graph.close().await?;
    } else {
        tracing::debug!("confirm_candidate: skipping graph edge write in socket mode (graceful degradation)");
    }

    Ok(())
}

/// Tombstone the record and remove all HasGotcha edges.
async fn delete_candidate(cwd: &Path, key: &str) -> Result<()> {
    let proxy = StoreProxy::open(cwd).await?;

    let mut record = proxy
        .get(key)
        .await?
        .ok_or_else(|| anyhow::anyhow!("record not found: {key}"))?;

    let gotcha: GotchaRecord = record
        .payload_as()
        .ok_or_else(|| anyhow::anyhow!("{key} is not a gotcha record"))?;

    let now = now_secs();
    record.lifecycle = RecordLifecycle::Tombstoned {
        reason: TombstoneReason::ManualDeletion,
        at: now,
    };
    record.updated_at = now;
    record.version.logical_clock += 1;
    record.version.wall_clock = now;

    proxy.put(key, &record).await?;

    if proxy.is_direct() {
        let store = proxy.into_store();
        let mut graph = Graph::load(store).await?;
        for af in &gotcha.affected_files {
            let file_key = format!("file:{af}");
            graph.remove_edge(&file_key, &EdgeKind::HasGotcha, key).await?;
        }
        graph.close().await?;
    } else {
        tracing::debug!("delete_candidate: skipping graph edge removal in socket mode (graceful degradation)");
    }

    Ok(())
}

/// Inline edit: rule and reason only.
/// For severity / affected_files / ref_url changes use `mati gotcha edit <key>`.
/// Returns `true` if the record was also confirmed.
async fn edit_inline(
    cwd: &Path,
    key: &str,
    gotcha: &GotchaRecord,
    lines: &mut io::Lines<io::StdinLock<'_>>,
    use_color: bool,
) -> Result<bool> {
    let rule_hint = truncate(&gotcha.rule, 60);
    eprint_prompt(&format!("Rule [{rule_hint}]: "), use_color);
    let rule_input = read_line(lines)?;
    let rule = if rule_input.is_empty() {
        gotcha.rule.clone()
    } else {
        rule_input
    };

    let reason_hint = truncate(&gotcha.reason, 60);
    eprint_prompt(&format!("Reason [{reason_hint}]: "), use_color);
    let reason_input = read_line(lines)?;
    let reason = if reason_input.is_empty() {
        gotcha.reason.clone()
    } else {
        reason_input
    };

    // Persist edits (still confirmed=false until user confirms below).
    let proxy = StoreProxy::open(cwd).await?;
    let mut record = proxy
        .get(key)
        .await?
        .ok_or_else(|| anyhow::anyhow!("record not found: {key}"))?;

    let now = now_secs();
    let updated_gotcha = GotchaRecord {
        rule: rule.clone(),
        reason: reason.clone(),
        severity: gotcha.severity.clone(),
        affected_files: gotcha.affected_files.clone(),
        ref_url: gotcha.ref_url.clone(),
        discovered_session: gotcha.discovered_session,
        confirmed: false, // still a candidate — confirm step below sets true
    };

    record.value = if reason.is_empty() {
        rule
    } else {
        format!("{} because {}", updated_gotcha.rule, updated_gotcha.reason)
    };
    record.payload = serde_json::to_value(&updated_gotcha).ok();
    record.updated_at = now;
    record.version.logical_clock += 1;
    record.version.wall_clock = now;
    record.quality = quality::analyze(&record);

    proxy.put(key, &record).await?;
    proxy.close().await?;

    // Ask whether to confirm after the edit.
    eprint_prompt("Confirm now? [Y/n]: ", use_color);
    let ans = read_line(lines)?;
    if ans.is_empty() || ans.to_lowercase().starts_with('y') {
        confirm_candidate(cwd, key).await?;
        let (green, reset) = if use_color { (colors::GREEN, colors::RESET) } else { ("", "") };
        eprintln!("{green}✓{reset} Edited and confirmed.");
        Ok(true)
    } else {
        eprintln!("Saved edits. Still unconfirmed — will reappear in next `mati review`.");
        Ok(false)
    }
}

// ── Shared helpers ────────────────────────────────────────────────────────────

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() > max {
        format!("{}…", &s[..max.saturating_sub(1)])
    } else {
        s.to_string()
    }
}

fn eprint_prompt(msg: &str, use_color: bool) {
    if use_color {
        eprint!("{}{}{} ", colors::BLUE, msg, colors::RESET);
    } else {
        eprint!("{msg} ");
    }
    let _ = io::stderr().flush();
}

fn read_line(lines: &mut io::Lines<io::StdinLock<'_>>) -> Result<String> {
    match lines.next() {
        Some(Ok(line)) => Ok(line.trim().to_string()),
        Some(Err(e)) => Err(e.into()),
        None => Ok(String::new()),
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use mati_core::store::{
        Category, ConfidenceScore, Priority, QualityScore, RecordVersion, StalenessScore,
    };

    fn make_gotcha_record(confirmed: bool) -> GotchaRecord {
        GotchaRecord {
            rule: "Always check db.rs when editing this file.".to_string(),
            reason: "Co-change signal from git history.".to_string(),
            severity: Priority::Normal,
            affected_files: vec!["src/main.rs".to_string()],
            ref_url: None,
            discovered_session: 0,
            confirmed,
        }
    }

    fn make_record(key: &str, gotcha: &GotchaRecord, quality_value: f32) -> Record {
        let now = 1_710_520_800u64;
        Record {
            key: key.to_string(),
            value: gotcha.rule.clone(),
            payload: serde_json::to_value(gotcha).ok(),
            category: Category::Gotcha,
            priority: Priority::Normal,
            tags: vec!["co-change".to_string()],
            created_at: now,
            updated_at: now,
            ref_url: None,
            staleness: StalenessScore::fresh(),
            lifecycle: RecordLifecycle::Active,
            version: RecordVersion {
                device_id: uuid::Uuid::new_v4(),
                logical_clock: 1,
                wall_clock: now,
            },
            quality: QualityScore {
                value: quality_value,
                tier: if quality_value >= 0.7 {
                    mati_core::store::QualityTier::Good
                } else if quality_value >= 0.4 {
                    mati_core::store::QualityTier::Acceptable
                } else {
                    mati_core::store::QualityTier::Poor
                },
                signals: vec![],
                computed_at: 0,
            },
            access_count: 0,
            last_accessed: 0,
            source: RecordSource::StaticAnalysis,
            confidence: ConfidenceScore {
                value: 0.45,
                confirmation_count: 0,
                contributor_count: 1,
                last_challenged: None,
                challenge_count: 0,
            },
            gap_analysis_score: 0.0,
        }
    }

    #[test]
    fn collect_candidates_filters_confirmed() {
        let confirmed = make_record(
            "gotcha:already-confirmed",
            &make_gotcha_record(true),
            0.50,
        );
        let candidate = make_record(
            "gotcha:needs-review",
            &make_gotcha_record(false),
            0.50,
        );

        // confirmed=true records must NOT appear
        let confirmed_payload: GotchaRecord =
            confirmed.payload_as().unwrap();
        assert!(confirmed_payload.confirmed);

        // confirmed=false records must appear
        let candidate_payload: GotchaRecord =
            candidate.payload_as().unwrap();
        assert!(!candidate_payload.confirmed);
    }

    #[test]
    fn collect_candidates_includes_low_quality() {
        // Layer 0 stubs (Suppressed tier, quality < 0.4) must be surfaced for review
        // so developers can improve + confirm them. The injection gate is enforced
        // separately by the pre-read hook.
        let low_quality = make_record("gotcha:low-q", &make_gotcha_record(false), 0.35);
        assert!(
            low_quality.quality.value < 0.4,
            "quality 0.35 is in the Suppressed tier"
        );
        let payload: GotchaRecord = low_quality.payload_as().unwrap();
        // confirmed=false + Active lifecycle → should be a candidate regardless of quality
        assert!(!payload.confirmed, "unconfirmed gotcha is a review candidate");
    }

    #[test]
    fn collect_candidates_sorts_by_access_count() {
        let mut low = make_record("gotcha:low-access", &make_gotcha_record(false), 0.50);
        low.access_count = 2;
        let mut high = make_record("gotcha:high-access", &make_gotcha_record(false), 0.50);
        high.access_count = 10;

        let mut candidates = [low, high];
        candidates.sort_by(|a, b| b.access_count.cmp(&a.access_count));

        assert_eq!(candidates[0].key, "gotcha:high-access");
        assert_eq!(candidates[1].key, "gotcha:low-access");
    }

    #[test]
    fn truncate_at_boundary() {
        let short = "hello";
        assert_eq!(truncate(short, 10), "hello");

        let long = "this is a very long string that exceeds the limit";
        let result = truncate(long, 10);
        assert!(result.ends_with('…'), "should end with ellipsis");
        // Check char count (not byte length) — '…' is 3 bytes but 1 char.
        assert!(result.chars().count() <= 10);
    }

    #[test]
    fn truncate_exact_length() {
        let s = "exactlen!";
        assert_eq!(truncate(s, 9), "exactlen!", "exact length should not truncate");
    }
}
